### ISSUE TITLE
Результат выполнения скрипта Current balance: 0

### ISSUE THREAD

**Issue by d3nis-web** [deademo/privat24_api_client#1]
Ответ всегда Current balance: 0
Это проблема на стороне приват24 ?

**Comment by khylia-dev** [comment]
Попытался воспроизвести проблему локально - не получилось.
```
docker run -it deademo/privat24_api_client
/privat24 # venv/bin/python console_interface.py -m xxxxxx -p xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -c xxxxxxxxxxxxxxxx -b
Current balance: 2,301.16
```
Судя по всему проблема не на стороне Приват24.
Проверил на Alpine Linux с Python 3.6.3 и Windows 10 с Python 3.6.3.

Скажите, какие параметры Вы используете для запуска скрипта, за исключением -m, -p и -c?
Может быть на карте действительно 0? 
Может быть Вы ошибочно указали не правильную карту?

**Comment by d3nis-web** [comment]
Всё, проблема решена, все корректно работает.
Номер карты отличался на один символ.
